version: 0.2
            
phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm run build
      - npm run webpack:production
  post_build:
    commands:
      - aws s3 rm s3://carsonhoward.com --recursive
      - aws s3 cp build s3://carsonhoward.com --recursive

artifacts:
  files:
    - build/index.html
    - build/Index.js
    - build/styles.css
  base-directory: .